# name: Terraform Deployment

# on:
#   push:
#     branches:
#       - main

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     env:
#       TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
#       TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#       TF_VAR_secret_key: ${{ secrets.AWS_SECRET_KEY }}

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         terraform_version: 1.0.0

#     - name: Terraform Init
#       run: terraform init

#     - name: Terraform Plan
#       run: terraform plan

#     # - name: Terraform Apply
#     #   run: terraform apply -auto-approve
    
#     - name: Terraform Apply
#       run: terraform destroy -auto-approve

#     # Add more steps as needed for your specific workflow.

